"""Add imports transaction fields and models

Revision ID: 233cb248c9ec
Revises: a74e3e859c78
Create Date: 2025-04-30 08:53:31.861456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233cb248c9ec'
down_revision = 'a74e3e859c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_reference', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('imported_records', sa.Integer(), nullable=True),
    sa.Column('duplicate_records', sa.Integer(), nullable=True),
    sa.Column('error_records', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_reference')
    )
    op.create_table('category_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=True),
    sa.Column('is_regex', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_category_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description_pattern', sa.String(length=255), nullable=False),
    sa.Column('bank_reference_pattern', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description_pattern', 'bank_reference_pattern', 'organization_id', name='unique_transaction_pattern')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('bank_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('imported_from', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('import_batch_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_transaction_hash'), ['transaction_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_hash'))
        batch_op.drop_column('import_batch_id')
        batch_op.drop_column('imported_from')
        batch_op.drop_column('bank_reference')
        batch_op.drop_column('transaction_hash')

    op.drop_table('transaction_category_history')
    op.drop_table('category_keywords')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
