"""Add fields for import transaction feature and account number

Revision ID: 547264be36d4
Revises: fca4cbb37741
Create Date: 2025-04-30 09:09:33.161186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547264be36d4'
down_revision = 'fca4cbb37741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
