"""Add imports transaction fields and models

Revision ID: fca4cbb37741
Revises: 233cb248c9ec
Create Date: 2025-04-30 08:57:02.921635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca4cbb37741'
down_revision = '233cb248c9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_transaction_hash')
        batch_op.create_index('ix_transaction_hash', ['transaction_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transaction_hash')
        batch_op.create_index('ix_transactions_transaction_hash', ['transaction_hash'], unique=False)

    # ### end Alembic commands ###
